= CSM Docker: SLE Go

A SLE Server GoLang Docker image used for RPM builds.

Available images can only be seen by querying the Docker API or
https://artifactory.algol60.net/artifactory/csm-docker/stable/csm-docker-sle-go[visiting the registry itself].

== Building

The provided `Makefile` adds Jenkins Pipeline variables to the `docker build` command. The commands below are for use outside the CSM Jenkins Pipeline.

[source,bash]
----
export DOCKER_BUILDKIT=1
export SLES_REGISTRATION_CODE=<registration_code>

make image

docker run -it csm-docker-sle-go:1.19
----

== Running

[source,bash]
----
# Go Version
docker run -it artifactory.algol60.net/csm-docker/stable/csm-docker-sle-go:1.19

# Go Version and distro
docker run -it artifactory.algol60.net/csm-docker/stable/csm-docker-sle-go:1.19-SLES15.4

# Go Version and distro
docker run -it artifactory.algol60.net/csm-docker/stable/csm-docker-sle-go:1.19-SLES15.3
----

== GoLang Version(s)

The version is controlled by the `Jenkinsfile`.

Unstable image tags will publish using these tags:

* `[DISTRO]-[HASH]`
* `[DISTRO]-[HASH]-[TIMESTAMP]`

Stable image tags will publish using these tags:

.The `[MAJOR.MINOR]` image is only created against the latest distro.
* `[MAJOR.MINOR]`
* `[MAJOR.MINOR]-[DISTRO]`
* `[MAJOR.MINOR]-[DISTRO]-[HASH]`
* `[MAJOR.MINOR]-[DISTRO]-[HASH]-[TIMESTAMP]`

=== Updating GO

To use a newer version of GoLang, update the `Jenkinsfile` with a new `goVersion`. The latest Go version can
be obtained from https://go.dev/VERSION?m=text[https://go.dev/VERSION?m=text].